import {readFileSync} from 'node:fs';

const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repository = 'https://github.com/sverma/fantasytales';
export const publicPaths = ['/', '/about', '/open-source', '/privacy', '/guidelines'];
const pages = {
  '/': ['Fantasy Tales — Free, Open-Source, AI-Powered Dating', 'Discover Fantasy Tales, a free, open-source dating community with AI-powered profile ratings, private profiles, and thoughtful, mutual introductions.'],
  '/about': ['About Fantasy Tales — Smart AI-Powered Dating', 'Learn how Fantasy Tales brings together free dating, AI-powered profile ratings, and mutual introductions in a community for adults.'],
  '/open-source': ['Open-Source Dating Software — Fantasy Tales', 'Explore the complete Fantasy Tales dating application on GitHub. Free MIT-licensed source code, self-hosting instructions, and optional AI-powered profile ratings.'],
  '/privacy': ['Privacy Notice — Fantasy Tales', 'How Fantasy Tales handles account details, WhatsApp numbers, private conversations, visit logs, and optional AI profile assessments.'],
  '/guidelines': ['Community Guidelines — Fantasy Tales', 'Fantasy Tales is an adults-only dating community built around consent, respectful introductions, and privacy. Read the community guidelines.'],
};
const articles = {
  '/about': `<span class="kicker">A little more about us</span><h1>Real people.<br><em>Thoughtful beginnings.</em></h1><p class="intro">Fantasy Tales is free, open-source dating for adults who want to start with a conversation.</p><h2>A hello, on your terms</h2><p>Create an account, add your name and WhatsApp number, and explore the member profiles. Save a profile that interests you or send a thoughtful introduction. Chat opens after that introduction is accepted.</p><h2>Smart tools, human choices</h2><p>Our AI-powered profile ratings consider profile quality and a subjective visual impression from photos. Changed profiles are checked daily when AI ratings are enabled. A score does not verify identity or predict compatibility. You decide who feels right for you.</p><h2>Free to join. Open to understand.</h2><p>There is no membership fee to join the community, explore profiles, or send introductions. The application source is openly available under the MIT license. Self-hosting and optional third-party AI services can have operating costs.</p><a class="button primary" href="/app#welcome">Join Fantasy Tales <span aria-hidden="true">↗</span></a>`,
  '/open-source': `<span class="kicker">Built in the open</span><h1>Open code.<br><em>More possibility.</em></h1><p class="intro">Fantasy Tales is free, open-source dating software, released under the MIT license.</p><h2>Explore the complete application</h2><p>The repository includes the web interface, server, database schema, six-digit PIN sign-in, mutual introductions, messaging, administration, AI rating worker, application metrics, and automated tests.</p><p>Developers can inspect the code, suggest improvements, or run their own instance. Node.js 24 and SQLite keep the core application small. Optional AI ratings use an operator-provided OpenAI API key.</p><div class="actions"><a class="button primary" href="${repository}" target="_blank" rel="noopener noreferrer">View source on GitHub ↗</a><a class="button secondary" href="${repository}/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">Read the MIT license ↗</a></div><h2>Open source, private member information</h2><p>The repository contains code and synthetic test fixtures. Accounts, phone numbers, member photos, conversations, activity logs, exports, and credentials are not part of the open-source release.</p><h2>Run your own community</h2><p>Follow the repository’s setup and deployment instructions. Hosting and optional API usage are paid by the operator; the source code is free to use under its license.</p>`,
  '/privacy': `<span class="kicker">Your information</span><h1>A clear view<br><em>of privacy.</em></h1><p class="intro">This notice explains how the Fantasy Tales community handles information when you browse, sign up, and connect.</p><h2>Account and contact details</h2><p>We store your username, chosen name, hashed sign-in credential, consent timestamps, and WhatsApp number. A WhatsApp number with country code is required before viewing profiles. We do not verify the number or send automated WhatsApp messages. Administrators can access member contact details and private connection exports.</p><h2>Profiles and conversations</h2><p>Member profiles and photos require sign-in and completed contact information. An introduction can be accepted, declined, or withdrawn. Messaging requires an accepted introduction. Sharing your WhatsApp number with the recipient is optional and occurs only after acceptance.</p><h2>Cookies and activity records</h2><p>Essential session cookies support sign-in and security. We record IP addresses, visit times, and activity such as page views, profile opens, and introductions. Application visit logs and administrator action history are retained for 30 days. Separate server access and security logs support site operation and abuse prevention. Private backups retain seven days of recovery history.</p><h2>AI profile ratings</h2><p>When enabled by the administrator, profile biographies, headlines, and photos are sent to OpenAI for a subjective assessment. Account phone numbers, sign-in credentials, messages, and visit logs are excluded from that assessment. Scores are shown to signed-in members. They do not verify identity or predict compatibility.</p><h2>Your choices</h2><p>Update your account details or PIN in Account. Members can delete their accounts, introductions, and messages there; retained security logs and backups expire separately. Profile owners can edit their biographies and should contact the community organizer for profile removal. Members can block or report profiles.</p><h2>Photo privacy</h2><p>Access controls limit who can view photos, and the interface discourages copying. A website cannot reliably prevent screenshots, screen recordings, or photographs taken with another device. Please respect other members’ privacy.</p><h2>Open-source code</h2><p>Publishing the application source does not publish its private database, member photos, messages, logs, exports, or API keys.</p>`,
  '/guidelines': `<span class="kicker">A community with care</span><h1>Mutual interest.<br><em>Mutual respect.</em></h1><p class="intro">Fantasy Tales is for consenting adults aged 18 or older.</p><h2>Start with consent</h2><p>A profile is an invitation to introduce yourself, not permission to demand attention. Respect declined introductions, boundaries, and a decision to stop talking. Share contact information only when you choose to.</p><h2>Be yourself, be considerate</h2><p>Use photos you have permission to share. Do not impersonate others, harass members, send scams, or publish someone’s private information. Profiles and photos must represent consenting adults.</p><h2>Keep private things private</h2><p>Do not copy, repost, or distribute another member’s photos or conversations without permission. Use the block and report controls when something feels wrong.</p><h2>People are more than a rating</h2><p>AI scores are subjective profile assessments. They are not a measure of a person’s worth, a verification badge, or a promise of compatibility. Your preferences and conversations matter.</p><h2>Make your own choices</h2><p>Take your time getting to know someone. Meeting or sharing contact details is always your choice. This application supports dating and mutual introductions; it does not sell or book sexual services.</p>`,
};

export function publicPage(path, origin, verification = '') {
  const canonicalOrigin = new URL(origin).origin;
  const [title, description] = pages[path];
  const template = readFileSync(new URL('./public/index.html', import.meta.url), 'utf8');
  const canonical = canonicalOrigin + path;
  const schema = {'@context':'https://schema.org','@type':'WebSite',name:'Fantasy Tales',url:canonicalOrigin+'/',description:pages['/'][1],sameAs:[repository]};
  return template.replaceAll('{{TITLE}}', escape(title)).replaceAll('{{DESCRIPTION}}', escape(description))
    .replaceAll('{{CANONICAL}}', escape(canonical)).replaceAll('{{ORIGIN}}', escape(canonicalOrigin))
    .replace('{{VERIFICATION}}', verification ? `<meta name="google-site-verification" content="${escape(verification)}">` : '')
    .replace('{{SCHEMA}}', JSON.stringify(schema).replaceAll('<','\\u003c'))
    .replace('{{CONTENT}}', path === '/' ? readFileSync(new URL('./public/home.html', import.meta.url),'utf8') : `<section class="article wrap">${articles[path]}</section>`);
}

export function robots(origin) {
  return `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /media/\nDisallow: /private/\nDisallow: /data/\nDisallow: /ganglia/\nDisallow: /ganglia2/\n\nSitemap: ${new URL(origin).origin}/sitemap.xml\n`;
}
export function sitemap(origin) {
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${publicPaths.map(path=>`<url><loc>${escape(new URL(origin).origin+path)}</loc></url>`).join('')}</urlset>\n`;
}
